service: pedirPizzas
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  profile: alejandro-marin
  environment:
    REGION: ${self:provider.region}
    PENDING_ORDER_QUEUE:
      Ref: PendingOrderQueue
    PENDING_ORDER_QUEUE_NAME: PendingOrderQueue
    COMPLETED_ORDER_TABLE: CompletedOrderTable

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource: "arn:aws:sqs:${self:provider.region}:*:${self:provider.environment.PENDING_ORDER_QUEUE_NAME}"
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.COMPLETED_ORDER_TABLE}"

functions:
  hacerPedido:
    handler: handler.hacerPedido
    events:
      - http:
          method: post
          path: pedido
  prepararPedido:
    handler: handler.prepararPedido
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ${self:provider.environment.PENDING_ORDER_QUEUE_NAME}
              - Arn
  enviarPedido:
      handler: handler.enviarPedido
      events:
        - stream:
            type: dynamobd
            batchSize: 1
            startingPosition: LATEST
            arn:
              Fn::GetAtt:
                - CompletedOrdersTable
                - StreamArn

resources:
  Resources:
    PendingOrderQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "${self:provider.environment.PENDING_ORDER_QUEUE_NAME}"
    CompletedOrdersTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
        - AttributeName: "orderId"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "orderId"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.COMPLETED_ORDER_TABLE}